feat: adapt platform danger zone section, extend explanation around p…
meshcloud/meshcloud-docs pull request #604
Opened 2023-01-26 18:43 UTC by uleMeshcloud

…ossible states

CU-861m6kd0x

2023-01-27 14:24 UTC, tfelix approved these changes

2023-01-27 14:24 UTC, tfelix commented on docs/administration.platforms.md
> +**Deprecation** will prevent the meshPlatform from being selected for new meshTenants. Existing meshTenants of this meshPlatform will still be replicated and can still be accessed via the meshPanel.
d: maybe also write that an indicator will tell people that those platforms are deprecated visually.

2023-01-30 06:55 UTC, sttomm requested changes

2023-01-30 06:55 UTC, sttomm commented on docs/administration.platforms.md
> +### Platform Danger Zone
d: Perhaps better split it into 2 headlines. One for Deprecation and one for Deletion. I think that provides a better overview on what this section is about. Danger Zone leaves room for a lot of interpretation. But reading about deprecation and deletion you directly know what it is about.

2023-01-30 06:55 UTC, sttomm commented on docs/administration.platforms.md
> +**Deletion** will make the meshPlatform not selectable for new meshTenants and existing meshTenants not accessible via meshPanel anymore. No more replication will be executed. Metering instead will s
d: Do you want to merge this after your PR about actually doing the tenant deletion when a platform is deleted? If that's the case, which would make sense to me, you have to change the description of Deletion. We will actually delete all tenants right away and also remove the metering and replicator config. So the platform will be completely unaccessible via meshStack and not recoverable.

2023-03-15 13:52 UTC, sttomm commented on docs/administration.platforms.md
> +**Deletion** will make the meshPlatform not selectable for new meshTenants and existing meshTenants not accessible via meshPanel anymore. No more replication will be executed. Once you delete a meshP
```suggestion
**Deletion** will make the meshPlatform not selectable for new meshTenants and existing meshTenants not accessible via meshPanel anymore. No more replication will be executed. Once you delete a meshPlatform, meshStack will automatically delete all meshTenants of the meshPlatform without deleting the platform tenants in the cloud platform. The deletion process of a meshPlatform will also remove the replicator and metering configurations. Therefore, your meshPlatform will be completely inaccessible via meshStack and can not be recovered. As meshStack does not delete or do any updates on platform tenants themself when a meshPlatform is deleted, direct access in the cloud platform to the platform tenants is still possible.
```

2023-03-15 13:59 UTC, uleMeshcloud commented on docs/administration.platforms.md
> +**Deletion** will make the meshPlatform not selectable for new meshTenants and existing meshTenants not accessible via meshPanel anymore. No more replication will be executed. Once you delete a meshP
fixed to themselves

2023-03-15 16:06 UTC, PolinaSadykova commented on docs/administration.platforms.md
```suggestion
**Deprecation** will prevent the meshPlatform from being selected for new meshTenants. Existing meshTenants of this meshPlatform will still be replicated and can still be accessed via the meshPanel. Your users can recognize a meshTenant of a deprecated meshPlatform by a yellow bubble on the platform icon in the "Projects Overview" screen on the Customer Control plane. If the user is on the tenant control plane, a yellow status label will appear in the header of the control plane. You can also **undo the deprecation**. This allows your users to select the meshPlatform for new meshTenants again.

```

2023-03-15 16:10 UTC, PolinaSadykova commented on docs/administration.platforms.md
> -Deactivation will make the meshPlatform not selectable anymore for new meshTenants, existing meshTenants won't be accessible via meshPanel anymore and no more replication will be executed. Metering i
Will it be also on the screen or not?

2023-03-15 16:12 UTC, PolinaSadykova commented on docs/administration.platforms.md
> +4. Click on `Delete meshPlatform` button and confirm the deletion with its identifier. A deletion **can not be reverted**.
```suggestion
### Delete Platform

**Deletion** will make the meshPlatform not selectable for new meshTenants and existing meshTenants not accessible via meshPanel anymore. No more replication will be executed. Once you delete a meshPlatform, meshStack will automatically delete all meshTenants of the meshPlatform without deleting the platform tenants in the cloud platform. The deletion process of a meshPlatform will also remove the replicator and metering configurations. Therefore, your meshPlatform will be completely inaccessible via meshStack and can not be recovered. As meshStack does not delete or do any updates on platform tenants themselves when a meshPlatform is deleted, direct access in the cloud platform to the platform tenants is still possible.

1. Navigate to **Platforms** > **meshPlatforms**.
2. Select the meshPlatform.
3. Navigate to **Danger Zone**.
4. Click on `Delete meshPlatform` button and confirm the deletion with its identifier. A deletion **can not be reverted**.
```

2023-03-15 16:13 UTC, PolinaSadykova commented on docs/administration.platforms.md
I could not find tenant control plane status ( e.g. depreciation) Could you help me with which screen it is?

2023-03-15 16:13 UTC, PolinaSadykova approved these changes

2023-03-15 16:38 UTC, merged