Update meshcloud.index.md
meshcloud/meshcloud-docs pull request #785
Opened 2024-04-16 05:27 UTC by chewbeccy

2024-04-16 06:29 UTC, henryde approved these changes

2024-04-16 06:33 UTC, henryde commented on docs/meshcloud.index.md
> +Follow (https://docs.meshcloud.io/blog) which provides atom and rss feeds. Or follow either one of (https://docs.meshcloud.io/blog/feed.xml) and (https://docs.meshcloud.io/blog/atom.xml) directly.
```suggestion
Follow (/blog)[release notes] which provides atom and rss feeds. Or follow either one of (/blog/feed.xml)[rss] and (/blog/atom.xml)[atom] directly. 
```

2024-04-16 07:25 UTC, Jelledb requested changes

2024-04-16 07:25 UTC, Jelledb commented on docs/meshcloud.index.md
> +Follow (https://docs.meshcloud.io/blog) which provides atom and rss feeds. Or follow either one of (https://docs.meshcloud.io/blog/feed.xml) and (https://docs.meshcloud.io/blog/atom.xml) directly.
I propose the following. I also added the newsletter & made it bullet points so it's easier to process.

```suggestion
We release regularly and provide weekly updates. If you want to stay on top of changes in meshStack you can use the following: 

- Have a look at the roadmap on the website under [www.meshcloud.io](https://www.meshcloud.io/en/product/).
- Subscribe to the [Product Newsletter](https://share.hsforms.com/1AbELCsdRRP6EaCkm1UeATwc0hrp) which is sent out every two weeks summarizing the most important changes.
- Have a look at the [release notes](https://docs.meshcloud.io/blog) or follow either one of [RSS](https://docs.meshcloud.io/blog/feed.xml) or [atom](https://docs.meshcloud.io/blog/atom.xml) directly. 
```

2024-04-22 06:04 UTC, Jelledb approved these changes

2024-04-22 07:15 UTC, merged